name: CI_PIPELINE

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout_code
        uses: actions/checkout@v5

      - name: Setup_Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install_dependencies
        run: npm install

      - name: Run_tests
        run: npm test
